var m=1;
let content = [
    {
        id: m++,
        title: "1959 | Round2Hell | R2H",
        channel: "Round 2 Hell",
        views: "41.6M",
        uploadedOn: "3 weeks ago",
        avatar: "https://res-kol.noxgroup.com/noxinfluencer/youtube/avatar/ff8ca8bf6b6181305cce9c0f9e3a03c4.png",
        thumbnail: "https://i.ytimg.com/vi/xhsIMUmd4sY/maxresdefault.jpg",
        duration: "51:22",
    },
    {
        id: m++,
        title: "ZOMBIE | The Living Dead | Round2Hell | R2H",
        channel: "Round 2 Hell",
        views: "58.28M",
        uploadedOn: "5 months ago",
        avatar: "https://res-kol.noxgroup.com/noxinfluencer/youtube/avatar/ff8ca8bf6b6181305cce9c0f9e3a03c4.png",
        thumbnail: "https://i.ytimg.com/vi/RqLFXpuZFFk/maxresdefault.jpg",
        duration: "40:34",
    },
    {
        id: m++,
        title: "DECODE OR DIE | D.O.D | Round2hell | R2h",
        channel: "Round 2 Hell",
        views: "53M",
        uploadedOn: "8 months ago",
        avatar: "https://res-kol.noxgroup.com/noxinfluencer/youtube/avatar/ff8ca8bf6b6181305cce9c0f9e3a03c4.png",
        thumbnail: "https://i.ytimg.com/vi/MzwYN2eVv0E/maxresdefault.jpg",
        duration: "30:59",
    },
    {
        id: m++,
        title: "IPL SPOOF | CSK VS RCB | Round2hell | R2h",
        channel: "Round 2 Hell",
        views: "67.97M",
        uploadedOn: "10 months ago",
        avatar: "https://res-kol.noxgroup.com/noxinfluencer/youtube/avatar/ff8ca8bf6b6181305cce9c0f9e3a03c4.png",
        thumbnail: "https://i.ytimg.com/vi/0voI9HJD_Ns/maxresdefault.jpg",
        duration: "21:52",
    },
    {
        id: m++,
        title: "THE TIME FREEZE | ROUND2HELL | R2H",
        channel: "Round 2 Hell",
        views: "51.21M",
        uploadedOn: "1 year ago",
        avatar: "https://res-kol.noxgroup.com/noxinfluencer/youtube/avatar/ff8ca8bf6b6181305cce9c0f9e3a03c4.png",
        thumbnail: "https://i.ytimg.com/vi/_iERz3f27oQ/maxresdefault.jpg",
        duration: "25:18",
    },
    {
        id: m++,
        title: "SHOLAY | Round2hell | R2h",
        channel: "Round 2 Hell",
        views: "66.07M",
        uploadedOn: "2 years ago",
        avatar: "https://res-kol.noxgroup.com/noxinfluencer/youtube/avatar/ff8ca8bf6b6181305cce9c0f9e3a03c4.png",
        thumbnail: "https://i.ytimg.com/vi/jmJPHIRKqs8/maxresdefault.jpg",
        duration: "32:56",
    },
    {
        id: m++,
        title: "DUMB BLIND DEAF Part-3 | Round2hell | R2H",
        channel: "Round 2 Hell",
        views: "61.86M",
        uploadedOn: "1 year ago",
        avatar: "https://res-kol.noxgroup.com/noxinfluencer/youtube/avatar/ff8ca8bf6b6181305cce9c0f9e3a03c4.png",
        thumbnail: "https://i.ytimg.com/vi/i51er3rLPao/maxresdefault.jpg",
        duration: "16:40",
    },
    {
        id: m++,
        title: "PUBG | ROUND2HELL | R2H",
        channel: "Round 2 Hell",
        views: "67.63M",
        uploadedOn: "2 years ago",
        avatar: "https://res-kol.noxgroup.com/noxinfluencer/youtube/avatar/ff8ca8bf6b6181305cce9c0f9e3a03c4.png",
        thumbnail: "https://i.ytimg.com/vi/YA9oCJnkMJg/maxresdefault.jpg",
        duration: "33:47",
    },
    {
        id: m++,
        title: "ALADDIN | Round2hell | R2h",
        channel: "Round 2 Hell",
        views: "94.54M",
        uploadedOn: "2 years ago",
        avatar: "https://res-kol.noxgroup.com/noxinfluencer/youtube/avatar/ff8ca8bf6b6181305cce9c0f9e3a03c4.png",
        thumbnail: "https://i.ytimg.com/vi/F1t6zmvAnp0/maxresdefault.jpg",
        duration: "23:24",
    },
    {
        id: m++,
        title: "THE LAND OF BIGG BOSS | CARRYMINATI",
        channel: "CarryMinati",
        views: "42.52M",
        uploadedOn: "3 months ago",
        avatar: "https://res-kol.noxgroup.com/noxinfluencer/youtube/avatar/954483e332703134105f9860df2df9f2.png",
        thumbnail: "https://i.ytimg.com/vi/d7sewLjzNs0/maxresdefault.jpg",
        duration: "22:54",
    },
    {
        id: m++,
        title: "IDLES OF INDIA: GONE RIGHT",
        channel: "CarryMinati",
        views: "39.32M",
        uploadedOn: "1 year ago",
        avatar: "https://res-kol.noxgroup.com/noxinfluencer/youtube/avatar/954483e332703134105f9860df2df9f2.png",
        thumbnail: "https://i.ytimg.com/vi/abhuAYtmk58/maxresdefault.jpg",
        duration: "8:55",
    },
    {
        id: m++,
        title: "YALGAAR - CARRYMINATI X Wily Frenzy",
        channel: "CarryMinati",
        views: "255.47M",
        uploadedOn: "1 year ago",
        avatar: "https://res-kol.noxgroup.com/noxinfluencer/youtube/avatar/954483e332703134105f9860df2df9f2.png",
        thumbnail: "https://i.ytimg.com/vi/zzwRbKI2pn4/maxresdefault.jpg",
        duration: "3:15",
    },
    {
        id: m++,
        title: "FILM THE FLARE",
        channel: "CarryMinati",
        views: "47.21M",
        uploadedOn: "1 year ago",
        avatar: "https://res-kol.noxgroup.com/noxinfluencer/youtube/avatar/954483e332703134105f9860df2df9f2.png",
        thumbnail: "https://i.ytimg.com/vi/GOFQN8otiYs/maxresdefault.jpg",
        duration: "10:11",
    },
    {
        id: m++,
        title: "BIG BOSS BIG BOSS BIG BOSS PART 2 | CARRYMINATI",
        channel: "CarryMinati",
        views: "55.89M",
        uploadedOn: "1 year ago",
        avatar: "https://res-kol.noxgroup.com/noxinfluencer/youtube/avatar/954483e332703134105f9860df2df9f2.png",
        thumbnail: "https://i.ytimg.com/vi/9DAKh_XCk6g/maxresdefault.jpg",
        duration: "14:34",
    },
    {
        id: m++,
        title: "NOT A DARING SHOW FT. WAKAR ZAQA | CARRYMINATI",
        channel: "CarryMinati",
        views: "42.11M",
        uploadedOn: "1 year ago",
        avatar: "https://res-kol.noxgroup.com/noxinfluencer/youtube/avatar/954483e332703134105f9860df2df9f2.png",
        thumbnail: "https://i.ytimg.com/vi/SE7Yx_b0bE8/maxresdefault.jpg",
        duration: "8:57",
    },
    {
        id: m++,
        title: "I JUMPED OFF A PLANE | CARRYMINATI QnA 2019",
        channel: "CarryMinati",
        views: "13.17M",
        uploadedOn: "2 years ago",
        avatar: "https://res-kol.noxgroup.com/noxinfluencer/youtube/avatar/954483e332703134105f9860df2df9f2.png",
        thumbnail: "https://i.ytimg.com/vi/U8qEsK3liMI/maxresdefault.jpg",
        duration: "7:22",
    },
    {
        id: m++,
        title: "WEDDING OF THE YEAR (I'M INVITED!)",
        channel: "CarryMinati",
        views: "44.82M",
        uploadedOn: "2 years ago",
        avatar: "https://res-kol.noxgroup.com/noxinfluencer/youtube/avatar/954483e332703134105f9860df2df9f2.png",
        thumbnail: "https://i.ytimg.com/vi/XvyKSWfxM_w/maxresdefault.jpg",
        duration: "6:53",
    },
    {
        id: m++,
        title: "PUBG INDIA: REAL LIFE BATTLE ROYALE",
        channel: "CarryMinati",
        views: "36.37M",
        uploadedOn: "3 years ago",
        avatar: "https://res-kol.noxgroup.com/noxinfluencer/youtube/avatar/954483e332703134105f9860df2df9f2.png",
        thumbnail: "https://i.ytimg.com/vi/10y9yefd_xY/maxresdefault.jpg",
        duration: "16:21",
    },
    {
        id: m++,
        title: "Bubbly Sir Ki Lockdown Life! | Angry Masterji 15 | BB Ki Vines",
        channel: "BB Ki Vines",
        views: "46.04M",
        uploadedOn: "1 year ago",
        avatar: "https://res-kol.noxgroup.com/noxinfluencer/youtube/avatar/21c491ef577c49f439430ba76e27a438.png",
        thumbnail: "https://i.ytimg.com/vi/xgXnDnf0cHY/maxresdefault.jpg",
        duration: "6:42",
    },
    {
        id: m++,
        title: "BB Ki Vines- | Saalgira Party |",
        channel: "BB Ki Vines",
        views: "46.04M",
        uploadedOn: "3 years ago",
        avatar: "https://res-kol.noxgroup.com/noxinfluencer/youtube/avatar/21c491ef577c49f439430ba76e27a438.png",
        thumbnail: "https://i.ytimg.com/vi/e9sEYgOUeQA/maxresdefault.jpg",
        duration: "8:09",
    },
    {
        id: m++,
        title: "BB Ki Vines- | Titu Talks- Episode 2 ft. Johnny Sins |",
        channel: "BB Ki Vines",
        views: "36.97M",
        uploadedOn: "2 years ago",
        avatar: "https://res-kol.noxgroup.com/noxinfluencer/youtube/avatar/21c491ef577c49f439430ba76e27a438.png",
        thumbnail: "https://i.ytimg.com/vi/dLhKPgAotSQ/maxresdefault.jpg",
        duration: "7:54",
    },
    {
        id: m++,
        title: "BB Ki Vines- | Angry Masterji- Part 13 |",
        channel: "BB Ki Vines",
        views: "34.73M",
        uploadedOn: "3 years ago",
        avatar: "https://res-kol.noxgroup.com/noxinfluencer/youtube/avatar/21c491ef577c49f439430ba76e27a438.png",
        thumbnail: "https://i.ytimg.com/vi/Wg-ZgiQvlTY/maxresdefault.jpg",
        duration: "8:12",
    },
    {
        id: m++,
        title: "Body ka strongest hissa kya hai? | Angry Masterji 14 | BB Ki Vines",
        channel: "BB Ki Vines",
        views: "33.53M",
        uploadedOn: "2 years ago",
        avatar: "https://res-kol.noxgroup.com/noxinfluencer/youtube/avatar/21c491ef577c49f439430ba76e27a438.png",
        thumbnail: "https://i.ytimg.com/vi/e9sEYgOUeQA/maxresdefault.jpg",
        duration: "5:41",
    },
    {
        id: m++,
        title: "BB Ki Vines- | Itni Thand English Jhand |",
        channel: "BB Ki Vines",
        views: "33.45M",
        uploadedOn: "2 years ago",
        avatar: "https://res-kol.noxgroup.com/noxinfluencer/youtube/avatar/21c491ef577c49f439430ba76e27a438.png",
        thumbnail: "https://i.ytimg.com/vi/OIr31AZtVSk/maxresdefault.jpg",
        duration: "7:02",
    },
    {
        id: m++,
        title: "Bablooji's ex? | Chakhne Pe Charcha |BB Ki Vines",
        channel: "BB Ki Vines",
        views: "31.64M",
        uploadedOn: "2 years ago",
        avatar: "https://res-kol.noxgroup.com/noxinfluencer/youtube/avatar/21c491ef577c49f439430ba76e27a438.png",
        thumbnail: "https://i.ytimg.com/vi/szvRvkQRyGg/maxresdefault.jpg",
        duration: "6:22",
    },
    {
        id: m++,
        title: "BB Ki Vines- | Goa Chalte Hain |",
        channel: "BB Ki Vines",
        views: "31.43M",
        uploadedOn: "3 years ago",
        avatar: "https://res-kol.noxgroup.com/noxinfluencer/youtube/avatar/21c491ef577c49f439430ba76e27a438.png",
        thumbnail: "https://i.ytimg.com/vi/X79M2qxsrig/maxresdefault.jpg",
        duration: "8:11",
    },
    {
        id: m++,
        title: "Bubbly sir is hopeless dad?! | Angry Masterji- Part 12 | BB Ki Vines",
        channel: "BB Ki Vines",
        views: "31M",
        uploadedOn: "2 years ago",
        avatar: "https://res-kol.noxgroup.com/noxinfluencer/youtube/avatar/21c491ef577c49f439430ba76e27a438.png",
        thumbnail: "https://i.ytimg.com/vi/fMK6n3JqfMw/maxresdefault.jpg",
        duration: "8:12",
    },
    {
        id: m++,
        title: "Bubbly sir is hopeless dad?! | Angry Masterji- Part 12 | BB Ki Vines",
        channel: "BB Ki Vines",
        views: "31M",
        uploadedOn: "2 years ago",
        avatar: "https://res-kol.noxgroup.com/noxinfluencer/youtube/avatar/21c491ef577c49f439430ba76e27a438.png",
        thumbnail: "https://i.ytimg.com/vi/fMK6n3JqfMw/maxresdefault.jpg",
        duration: "8:12",
    }
];

export default content;